name: wobble
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - numpy>=1.11
  - scipy>=0.19.0
  - matplotlib>=1.5.3
  - astropy>=1.3
  - tqdm
  - ipython
  - cython
  - scikit-learn
  - h5py
  - pip
  - pip:
    - tensorflow
